resolution = [720, 1280]

[[attributes]]
name = "crowd"
toolType = "switch"
tagText = "c"

[[categories]]
name = "human"
    [[categories.subcategories]]
    name = "pedestrian"

    [[categories.subcategories]]
    name = "rider"

[[categories]]
name = "vehicle"
   [[categories.subcategories]]
    name = "car"

   [[categories.subcategories]]
    name = "truck"

   [[categories.subcategories]]
    name = "bus"

    [[categories.subcategories]]
    name = "train"

[[categories]]
name = "bike"
    [[categories.subcategories]]
    name = "motorcycle"

    [[categories.subcategories]]
    name = "bicycle"

[[categories]]
name = "traffic light"

[[categories]]
name = "traffic sign"
